name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Formatear Código con Black
        run: |
          source venv/bin/activate
          black --check .

      - name: Lint con Flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Tipos con Mypy
        run: |
          source venv/bin/activate
          mypy src/

      - name: Analizar Seguridad con Bandit
        run: |
          source venv/bin/activate
          bandit -r src/

      - name: Ejecutar Pruebas
        run: |
          source venv/bin/activate
          pytest

  build-deploy:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Código
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login a DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Push de Imagen Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tu-usuario/latam-challenge:latest

      - name: Desplegar en Servidor
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: usuario
          server-ip: servidor_ip
          remote-path: /path/to/deploy
          local-path: .
